/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.edu.unicartagena.poo.gui;

/**
 *
 * @author Carlos
 */
public class GuiPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GuiPrincipal
     */
    public GuiPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BarraMenu = new javax.swing.JMenuBar();
        MenuCiclistas = new javax.swing.JMenu();
        itemAgregarCiclistaUsuario = new javax.swing.JMenuItem();
        itemConsultaDatosUsuario = new javax.swing.JMenuItem();
        itemEditarDatosUsuario = new javax.swing.JMenuItem();
        itemEliminarDatosUsuario = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        SubmenuReporteUsuario = new javax.swing.JMenu();
        itemBuscarUsuarioxnombre = new javax.swing.JMenuItem();
        BuscarUsuarioxcorreo = new javax.swing.JMenuItem();
        MenuBicicleta = new javax.swing.JMenu();
        itemAgregarInformacionBicicleta = new javax.swing.JMenuItem();
        itemConsultarINFObicicleta = new javax.swing.JMenuItem();
        itemEditarInfoBicicleta = new javax.swing.JMenuItem();
        itemEliminarBicicleta = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        itemReporteBicicleta = new javax.swing.JMenu();
        itemBuscarBicicleta = new javax.swing.JMenuItem();
        MenuCompetencia = new javax.swing.JMenu();
        itemInformacionCompetencia = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(".::: GESTION DE BICICLETAS:::.");

        MenuCiclistas.setText("Ciclistas");
        MenuCiclistas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        itemAgregarCiclistaUsuario.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemAgregarCiclistaUsuario.setText("Agregar Ciclista");
        itemAgregarCiclistaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarCiclistaUsuarioActionPerformed(evt);
            }
        });
        MenuCiclistas.add(itemAgregarCiclistaUsuario);

        itemConsultaDatosUsuario.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemConsultaDatosUsuario.setText("Consultar Mis Datos ..");
        MenuCiclistas.add(itemConsultaDatosUsuario);

        itemEditarDatosUsuario.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemEditarDatosUsuario.setText("Editar Mis Datos..");
        MenuCiclistas.add(itemEditarDatosUsuario);

        itemEliminarDatosUsuario.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemEliminarDatosUsuario.setText("Eliminarme...");
        MenuCiclistas.add(itemEliminarDatosUsuario);
        MenuCiclistas.add(jSeparator1);

        SubmenuReporteUsuario.setText("Reportes");

        itemBuscarUsuarioxnombre.setText("Por Nombre");
        SubmenuReporteUsuario.add(itemBuscarUsuarioxnombre);

        BuscarUsuarioxcorreo.setText("Por Correo");
        BuscarUsuarioxcorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarUsuarioxcorreoActionPerformed(evt);
            }
        });
        SubmenuReporteUsuario.add(BuscarUsuarioxcorreo);

        MenuCiclistas.add(SubmenuReporteUsuario);

        BarraMenu.add(MenuCiclistas);

        MenuBicicleta.setText("Bicicleta");
        MenuBicicleta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        itemAgregarInformacionBicicleta.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemAgregarInformacionBicicleta.setText("Agregar Bicicleta...");
        itemAgregarInformacionBicicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAgregarInformacionBicicletaActionPerformed(evt);
            }
        });
        MenuBicicleta.add(itemAgregarInformacionBicicleta);

        itemConsultarINFObicicleta.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemConsultarINFObicicleta.setText("Consultar Mis Datos ..");
        itemConsultarINFObicicleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemConsultarINFObicicletaActionPerformed(evt);
            }
        });
        MenuBicicleta.add(itemConsultarINFObicicleta);

        itemEditarInfoBicicleta.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemEditarInfoBicicleta.setText("Editar Informacion..");
        MenuBicicleta.add(itemEditarInfoBicicleta);

        itemEliminarBicicleta.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemEliminarBicicleta.setText("Eliminar Bicicleta...");
        MenuBicicleta.add(itemEliminarBicicleta);
        MenuBicicleta.add(jSeparator2);

        itemReporteBicicleta.setText("Reportes..");

        itemBuscarBicicleta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        itemBuscarBicicleta.setText("Por Modelo");
        itemReporteBicicleta.add(itemBuscarBicicleta);

        MenuBicicleta.add(itemReporteBicicleta);

        BarraMenu.add(MenuBicicleta);

        MenuCompetencia.setText("Competencia");
        MenuCompetencia.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N

        itemInformacionCompetencia.setFont(new java.awt.Font("Arial", 3, 16)); // NOI18N
        itemInformacionCompetencia.setText("Informacion De La Competencia...");
        itemInformacionCompetencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemInformacionCompetenciaActionPerformed(evt);
            }
        });
        MenuCompetencia.add(itemInformacionCompetencia);

        BarraMenu.add(MenuCompetencia);

        setJMenuBar(BarraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarUsuarioxcorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarUsuarioxcorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarUsuarioxcorreoActionPerformed

    private void itemConsultarINFObicicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemConsultarINFObicicletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemConsultarINFObicicletaActionPerformed

    private void itemInformacionCompetenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemInformacionCompetenciaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemInformacionCompetenciaActionPerformed

    private void itemAgregarInformacionBicicletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarInformacionBicicletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itemAgregarInformacionBicicletaActionPerformed

    private void itemAgregarCiclistaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAgregarCiclistaUsuarioActionPerformed
       GuiUsuarios gui = new GuiUsuarios(this,true);
       gui.setLocationRelativeTo(this);
       gui.setVisible(true);
       
    }//GEN-LAST:event_itemAgregarCiclistaUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar BarraMenu;
    private javax.swing.JMenuItem BuscarUsuarioxcorreo;
    private javax.swing.JMenu MenuBicicleta;
    private javax.swing.JMenu MenuCiclistas;
    private javax.swing.JMenu MenuCompetencia;
    private javax.swing.JMenu SubmenuReporteUsuario;
    private javax.swing.JMenuItem itemAgregarCiclistaUsuario;
    private javax.swing.JMenuItem itemAgregarInformacionBicicleta;
    private javax.swing.JMenuItem itemBuscarBicicleta;
    private javax.swing.JMenuItem itemBuscarUsuarioxnombre;
    private javax.swing.JMenuItem itemConsultaDatosUsuario;
    private javax.swing.JMenuItem itemConsultarINFObicicleta;
    private javax.swing.JMenuItem itemEditarDatosUsuario;
    private javax.swing.JMenuItem itemEditarInfoBicicleta;
    private javax.swing.JMenuItem itemEliminarBicicleta;
    private javax.swing.JMenuItem itemEliminarDatosUsuario;
    private javax.swing.JMenuItem itemInformacionCompetencia;
    private javax.swing.JMenu itemReporteBicicleta;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
